# Generated by Django 3.1.2 on 2020-11-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
